# Generated by Django 5.0.6 on 2024-08-22 12:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('list_image', models.ImageField(upload_to='courses/')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='courses/images/')),
                ('detail_video', models.FileField(blank=True, null=True, upload_to='courses/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='teachers/videos/')),
                ('job_field', models.CharField(choices=[('IELTS 8', 'IELTS 8'), ('IELTS 7.5', 'IELTS 7.5'), ('IELTS 7', 'IELTS 7'), ('IELTS 6.5', 'IELTS 6.5'), ('IELTS 6', 'IELTS 6')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.course')),
            ],
        ),
    ]
